
USUARIOS_RANDOM = [
  {
    "nombre": "John",
    "apellido": "Doe",
    "direccion": "123 Main St",
    "edad": 30,
    "telefono": 5551234,
    "dni": 12345678,
    "rol": "user",
    "sexo": "M",
    "email": "johndoe@example.com",
    "contrasena": "password123"
  },
  {
    "nombre": "Jane",
    "apellido": "Doe",
    "direccion": "456 Elm St",
    "edad": 25,
    "telefono": 5555678,
    "dni": 87654321,
    "rol": "admin",
    "sexo": "F",
    "email": "janedoe@example.com",
    "contrasena": "password456"
  },
  {
    "nombre": "Bob",
    "apellido": "Smith",
    "direccion": "789 Oak St",
    "edad": 40,
    "telefono": 5559012,
    "dni": 11111111,
    "rol": "user",
    "sexo": "M",
    "email": "bobsmith@example.com",
    "contrasena": "password789"
  },
  {
    "nombre": "Alice",
    "apellido": "Johnson",
    "direccion": "321 Pine St",
    "edad": 35,
    "telefono": 5553456,
    "dni": 22222222,
    "rol": "admin",
    "sexo": "F",
    "email": "alicejohnson@example.com",
    "contrasena": "passwordabc"
  },
  {
    "nombre": "David",
    "apellido": "Lee",
    "direccion": "654 Maple St",
    "edad": 28,
    "telefono": 5557890,
    "dni": 33333333,
    "rol": "user",
    "sexo": "M",
    "email": "davidlee@example.com",
    "contrasena": "passworddef"
  },
  {
    "nombre": "Sarah",
    "apellido": "Kim",
    "direccion": "987 Cedar St",
    "edad": 33,
    "telefono": 5552345,
    "dni": 44444444,
    "rol": "admin",
    "sexo": "F",
    "email": "sarahkim@example.com",
    "contrasena": "passwordghi"
  },
  {
    "nombre": "Michael",
    "apellido": "Nguyen",
    "direccion": "246 Birch St",
    "edad": 42,
    "telefono": 5556789,
    "dni": 55555555,
    "rol": "user",
    "sexo": "M",
    "email": "michaelnguyen@example.com",
    "contrasena": "passwordjkl"
  },
  {
    "nombre": "Emily",
    "apellido": "Garcia",
    "direccion": "135 Walnut St",
    "edad": 27,
    "telefono": 5550123,
    "dni": 66666666,
    "rol": "admin",
    "sexo": "F",
    "email": "emilygarcia@example.com",
    "contrasena": "passwordmno"
  },
  {
    "nombre": "Daniel",
    "apellido": "Martinez",
    "direccion": "864 Pineapple St",
    "edad": 38,
    "telefono": 5554567,
    "dni": 77777777,
    "rol": "user",
    "sexo": "M",
    "email": "danielmartinez@example.com",
    "contrasena": "passwordpqr"
  },
  {
    "nombre": "Olivia",
    "apellido": "Lopez",
    "direccion": "579 Mango St",
    "edad": 31,
    "telefono": 5558901,
    "dni": 88888888,
    "rol": "admin",
    "sexo": "F",
    "email": "olivialopez@example.com",
    "contrasena": "passwordstu"
  },
  {
    "nombre": "William",
    "apellido": "Gonzalez",
    "direccion": "246 Apple St",
    "edad": 29,
    "telefono": 5552345,
    "dni": 99999999,
    "rol": "user",
    "sexo": "M",
    "email": "williamgonzalez@example.com",
    "contrasena": "passwordvwx"
  },
  {
    "nombre": "Sophia",
    "apellido": "Rodriguez",
    "direccion": "135 Banana St",
    "edad": 26,
    "telefono": 5556789,
    "dni": 10101010,
    "rol": "admin",
    "sexo": "F",
    "email": "sophiarodriguez@example.com",
    "contrasena": "passwordyz1"
  },
  {
    "nombre": "James",
    "apellido": "Perez",
    "direccion": "864 Orange St",
    "edad": 39,
    "telefono": 5551234,
    "dni": 12121212,
    "rol": "user",
    "sexo": "M",
    "email": "jamesperez@example.com",
    "contrasena": "password234"
  },
  {
    "nombre": "Isabella",
    "apellido": "Gomez",
    "direccion": "579 Lemon St",
    "edad": 32,
    "telefono": 5555678,
    "dni": 23232323,
    "rol": "admin",
    "sexo": "F",
    "email": "isabellagomez@example.com",
    "contrasena": "password567"
  },
  {
    "nombre": "Benjamin",
    "apellido": "Sanchez",
    "direccion": "246 Grape St",
    "edad": 30,
    "telefono": 5559012,
    "dni": 34343434,
    "rol": "user",
    "sexo": "M",
    "email": "benjaminsanchez@example.com",
    "contrasena": "password890"
  },
  {
    "nombre": "Mia",
    "apellido": "Rivera",
    "direccion": "135 Cherry St",
    "edad": 28,
    "telefono": 5553456,
    "dni": 45454545,
    "rol": "admin",
    "sexo": "F",
    "email": "miarivera@example.com",
    "contrasena": "passwordabc1"
  },
  {
    "nombre": "Ethan",
    "apellido": "Ramirez",
    "direccion": "864 Peach St",
    "edad": 41,
    "telefono": 5557890,
    "dni": 56565656,
    "rol": "user",
    "sexo": "M",
    "email": "ethanramirez@example.com",
    "contrasena": "passworddef1"
  },
  {
    "nombre": "Ava",
    "apellido": "Torres",
    "direccion": "579 Plum St",
    "edad": 33,
    "telefono": 5552345,
    "dni": 67676767,
    "rol": "admin",
    "sexo": "F",
    "email": "avatorres@example.com",
    "contrasena": "passwordghi1"
  },
  {
    "nombre": "Alexander",
    "apellido": "Collins",
    "direccion": "246 Pear St",
    "edad": 28,
    "telefono": 5556789,
    "dni": 78787878,
    "rol": "user",
    "sexo": "M",
    "email": "alexandercollins@example.com",
    "contrasena": "passwordjkl1"
  },
  {
    "nombre": "Charlotte",
    "apellido": "Reyes",
    "direccion": "135 Avocado St",
    "edad": 27,
    "telefono": 5550123,
    "dni": 89898989,
    "rol": "admin",
    "sexo": "F",
    "email": "charlottereyes@example.com",
    "contrasena": "passwordmno1"
  }
]
