version: '3'

services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root # Update the POSTGRES_USER environment variable
      POSTGRES_PASSWORD: Sup3rSecret0
      POSTGRES_DB: gym_database
    volumes:
      - gym_db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready","-d", "gym_database", "-U", "root"] # Update the user name in the healthcheck command
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - gym_network

  # app:
  #   build: .
  #   environment:
  #     DATABASE_URI: postgresql://root:Sup3rSecret0@postgres:5432/gym_database # Update the user name in the DATABASE_URI environment variable
  #     PORT: 5001
  #     DATABASE_PATH: "path"
  #     DATABASE_NAME: "gym_database"
  #     JWT_SECRET_KEY: "Sup3rSecret0"
  #     JWT_ACCESS_TOKEN_EXPIRES: 900
  #   ports:
  #     - "5001:5000"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

  #   healthcheck:
  #     test: ["CMD", "wget", "-qO-", "--spider", "http://localhost:5000/readyz"]

  #   networks:
  #     - gym_network

volumes:
  gym_db_data:


networks:
  gym_network: