from .usuario import Usuarios as UsuariosResource
from .usuario import Usuario as UsuarioResource
from .alumno import Alumnos as AlumnosResource
from .alumno import Alumno as AlumnoResource
from .profesor import Profesores as ProfesoresResource
from .profesor import Profesor as ProfesorResource
from .clases import Clase as ClasesResource
from .clases import Clases as ClasesResource
from .pagos import Pagos as PagosResource
from .pagos import Pago as PagoResource
from .planificaciones import PlanificacionesAlumnos as PlanificacionesAlumnosResource
from .planificaciones import PlanificacionAlumno as PlanificacionAlumnoResource
from .planificaciones import Planificaciones as PlanificacionesResource
from .planificaciones import Planificacion as PlanificacionResource
from .login import Login as LoginResource