"""segunda migracion

Revision ID: 38a6eed52f82
Revises: 
Create Date: 2023-10-28 14:56:22.365341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a6eed52f82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_alumno')
    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('altura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peso', sa.Integer(), nullable=True))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.drop_column('planilla_medica')

    with op.batch_alter_table('clase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.String(length=45), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)

    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planificacion', schema=None) as batch_op:
        batch_op.drop_column('nivel')

    with op.batch_alter_table('clase', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.drop_column('titulo')

    with op.batch_alter_table('alumno', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planilla_medica', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.drop_column('peso')
        batch_op.drop_column('altura')

    op.create_table('_alembic_tmp_alumno',
    sa.Column('id_alumno', sa.INTEGER(), nullable=False),
    sa.Column('altura', sa.INTEGER(), nullable=True),
    sa.Column('peso', sa.INTEGER(), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('estado', sa.VARCHAR(length=45), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_alumno')
    )
    # ### end Alembic commands ###
